AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-crud

  Sample SAM Template for lambda-crud


Parameters:
  DBName:
    Type: String
    Default: lambda_crud


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: java11
    CodeUri: .
    MemorySize: 1024
    Timeout: 90
    Environment:
      Variables:
        ENV: !Sub "${ENV}"
        JASYPT_PWD: !Sub "${JASYPT_PWD}"
        DB_URL: !Sub "${DB_URL}"
        DB_USER: !Sub "${DB_USER}"
        DB_PWD: !Sub "${DB_PWD}"

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Cors:
      AllowOrigin: "'*'"
    Properties:
      StageName: !Sub "${ENV}"

  SavePublisherHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.julianduru.learning.lambda.crud.handlers.publisher.SavePublisherHandler::handleRequest
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /publisher
            Method: POST
            RestApiId: !Ref ApiGatewayApi

  DataSource:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 10
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: !Ref DBName
      Engine: MySQL
      EngineVersion: '8.0'
      MasterUsername: !Sub "${DB_USER}"
      MasterUserPassword: !Sub "${DB_PWD}"
      DBName: !Ref DBName

Outputs:
  ApiURL:
    Value: !Sub 'https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'
    Description: URL for the API endpoint
  DBEndpoint:
    Value: !GetAtt DataSource.Endpoint.Address
    Export:
      Name: DBInstanceEndpoint
    Description: Endpoint URL for the MySQL RDS instance

