
version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
        - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

