
version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      PGDATA: /var/lib/postgresql/new_data
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
    volumes:
        - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db:
