

CREATE TABLE IF NOT EXISTS CUSTOMER(
    id SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL
);


-- INSERT STATEMENT
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('John', 'Doe', 'jd@yahoo.com');

